name: dbro_admin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  # sdk: '>=2.18.4 <3.0.0'
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  material_design_icons_flutter: ^7.0.7296
  flutter_staggered_animations: ^1.1.1
  loading_animation_widget: ^1.2.0+4
  flutter_feather_icons: ^2.0.0+1 #ICONS
  back_button_interceptor: ^7.0.0
  flutter_native_splash: ^2.2.16
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.0
  responsive_builder: ^0.7.0
  flutter_typeahead: ^5.0.2
  flutter_animate: ^4.2.0+1
  responsive_sizer: ^3.2.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  flutter_portal: ^1.1.4
  universal_html: ^2.2.3
  skeletonizer: ^0.7.0
  # url_strategy: ^0.2.0
  flutter_svg: ^2.0.7
  auto_route: ^7.8.0
  shimmer: ^3.0.0
  encrypt: ^5.0.1
  iconly: ^1.0.1 #ICONS
  fimber: ^0.7.0
  dartz: ^0.10.1
  intl: ^0.18.1
  faker: ^2.1.0
  uuid: ^4.3.3
  dio: ^5.3.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.0
  flutter_gen_runner: ^5.3.1

# RUN dart run flutter_native_splash:create
flutter_native_splash:
  color: "#f49f5f"

# ASSETS GENERATOR
# RUN flutter packages pub run build_runner build TO GENERATE ASSETS
flutter_gen:
  output: lib/ui_kit/generated_theme/
  assets:
    package_parameter_enabled: false

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  fonts:
    - family: HKGoretsk
      fonts:
        - asset: assets/fonts/hkgoretsk/HKGrotesk-Bold.otf
          weight: 700
        - asset: assets/fonts/hkgoretsk/HKGrotesk-BoldLegacy.otf
          weight: 800
        - asset: assets/fonts/hkgoretsk/HKGrotesk-Light.otf
          weight: 300
        - asset: assets/fonts/hkgoretsk/HKGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/hkgoretsk/HKGrotesk-Regular.otf
          weight: 400
        - asset: assets/fonts/hkgoretsk/HKGrotesk-SemiBold.otf
          weight: 600
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/inter/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/inter/Inter-SemiBold.otf
          weight: 600

  assets:
      - assets/background/
      - assets/image/
      - assets/logo/
      - assets/json/

      #FORMATTED IMAGE
      - assets/image/png/
