part of 'consts.dart';

class _ConstsApikey {
  const _ConstsApikey();
  String get SYSCONFIG_TYPE_LIST => 'SYSCONFIG_TYPE_LIST';
  String get SYSCONFIG_TYPE_CREATE => 'SYSCONFIG_TYPE_CREATE';

  String get SYSCONFIG_LIST => 'SYSCONFIG_LIST';
  String get SYSCONFIG_CREATE => 'SYSCONFIG_CREATE';

  String get PERMISSION_LIST => 'PERMISSION_LIST';
  String get PERMISSION_CREATE => 'PERMISSION_CREATE';

  String get LIST_MY_PERMISSION => 'PERMISSION_LIST_MY_PERMISSION';
  String get USER_LOGOUT => 'USER_LOGOUT';
}
